apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: external-svc
  labels:
    app: external-svc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobs-master
  labels:
    app: external-svc
rules:
  - apiGroups: [""]
    resources: ["jobs"]
    verbs: ["list","view","create"]
  
  - apiGroups: [""]
    resources: ["nodes", "nodes/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-svc-jobs-master
  labels:
    app: external-svc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobs-master
subjects:
  - kind: ServiceAccount
    namespace: default
    name: external-svc
